package com.exam.madding;
// Generated Aug 26, 2018 11:08:28 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Mschedule generated by hbm2java
 */
public class Mschedule  implements java.io.Serializable {


     private Date mdate;
     private String mname;
     private Integer dsprice;
     private Integer psprice;
     private Integer gsprice;
     private Integer ssprice;

    public Mschedule() {
    }

	
    public Mschedule(Date mdate) {
        this.mdate = mdate;
    }
    public Mschedule(Date mdate, String mname, Integer dsprice, Integer psprice, Integer gsprice, Integer ssprice) {
       this.mdate = mdate;
       this.mname = mname;
       this.dsprice = dsprice;
       this.psprice = psprice;
       this.gsprice = gsprice;
       this.ssprice = ssprice;
    }
   
    public Date getMdate() {
        return this.mdate;
    }
    
    public void setMdate(Date mdate) {
        this.mdate = mdate;
    }
    public String getMname() {
        return this.mname;
    }
    
    public void setMname(String mname) {
        this.mname = mname;
    }
    public Integer getDsprice() {
        return this.dsprice;
    }
    
    public void setDsprice(Integer dsprice) {
        this.dsprice = dsprice;
    }
    public Integer getPsprice() {
        return this.psprice;
    }
    
    public void setPsprice(Integer psprice) {
        this.psprice = psprice;
    }
    public Integer getGsprice() {
        return this.gsprice;
    }
    
    public void setGsprice(Integer gsprice) {
        this.gsprice = gsprice;
    }
    public Integer getSsprice() {
        return this.ssprice;
    }
    
    public void setSsprice(Integer ssprice) {
        this.ssprice = ssprice;
    }




}


