package com.exam.drscedule;
// Generated Aug 26, 2018 11:08:28 PM by Hibernate Tools 4.3.1



/**
 * Drtab generated by hbm2java
 */
public class Drtab  implements java.io.Serializable {


     private Integer id;

    public Integer getCharge() {
        return charge;
    }

    public void setCharge(Integer charge) {
        this.charge = charge;
    }
     private Integer charge;
     private String name;
     private String password;
     private String specialist;
     private String degree;
     private String day;
     private byte[] pic;
     private String vtime;

    public Drtab() {
    }

    public Drtab(String name, String password, String specialist, String degree, String day, byte[] pic, String vtime) {
       this.name = name;
       this.password = password;
       this.specialist = specialist;
       this.degree = degree;
       this.day = day;
       this.pic = pic;
       this.vtime = vtime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getSpecialist() {
        return this.specialist;
    }
    
    public void setSpecialist(String specialist) {
        this.specialist = specialist;
    }
    public String getDegree() {
        return this.degree;
    }
    
    public void setDegree(String degree) {
        this.degree = degree;
    }
    public String getDay() {
        return this.day;
    }
    
    public void setDay(String day) {
        this.day = day;
    }
    public byte[] getPic() {
        return this.pic;
    }
    
    public void setPic(byte[] pic) {
        this.pic = pic;
    }
    public String getVtime() {
        return this.vtime;
    }
    
    public void setVtime(String vtime) {
        this.vtime = vtime;
    }




}


